site_name: Carteira de Trabalho Digital
site_url: https://requisitos-de-software.github.io/2025.1-Carteira-de-Trabalho-Digital/

nav:
  - Home:
      - Sobre: index.md
  - Atas de Reunião:
    - Ata 1: atas/ata-1.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Aplicativo: planejamento/aplicativo.md
    - Aplicativos Analisados: planejamento/appsAnalisados.md
    - Metodologia: planejamento/metodologia.md

theme:
  logo: assets/logo-ctd.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt
